### ISSUE TITLE
macOS_Update_Helper does not start download

### ISSUE THREAD

**Issue by LEB-HIG** [vmware-samples/euc-samples#132]
the MacOS_Update_Helper starts the process but hangs indefinitely on the DEPNotify screen stating 'initializing installer'.

I have tried multiple options including caching the full OS installer in the helper pkg, both scenarios produce the same outcome of hanging at the initializing installer window.

[macOSUpdateHelperLog.txt](https://github.com/vmware-samples/euc-samples/files/4819701/macOSUpdateHelperLog.txt)
[log.txt](https://github.com/vmware-samples/euc-samples/files/4819702/log.txt)

**Comment by pevans00** [comment]
The path of the macOS installer is hardcoded on lines 89 & 95 of the macOSUpdateHelper.sh.  basically, can you confirm if you're putting the installer in /Applications/Install macOS Catalina.app/ ?  Otherwise, you may want to update those lines or where you're putting the installer.

It seems like this line is causing the issue (line 289):

"$installerPath" --agreetolicense --rebootdelay 60 --pidtosignal $$ > "$appLog" 2>&1 &

**Comment by LEB-HIG** [comment]
Yes, the installer is in /Applications (we used WorkspaceONE admin assistant to wrap the 22mb stub installer for easier delivery to clients).

**Comment by pevans00** [comment]
When it's running (may take a minute or two to get initialized), do you see a "/macOS Install Data/" folder get created?  This is where the OS update should get downloaded to.  Can you check the running processes to see if you see anything related to "os install"?  I forget the exact name of the process, but it usually takes up a decent % of the CPU.

**Comment by LEB-HIG** [comment]
As of this morning and a fresh boot, everything is working as expected...  odd, but I will close out this issue.
